- name: Install application binary
  hosts: my_vms
  become: yes

  vars:
    nginx_url: "http://nginx.org/packages/mainline/ubuntu/pool/nginx/n/nginx/nginx_1.19.1-1~focal_amd64.deb"
    nginx_package: "/tmp/nginx.deb"

  tasks:
      - name: Download the Nginx package
        ansible.builtin.get_url:
          url: "{{ nginx_url }}"
          dest: "{{ nginx_package }}"
          mode: '0644'

      - name: Install the Nginx package
        ansible.builtin.command:
          cmd: dpkg -i {{ nginx_package }}
        register: install_output
        ignore_errors: yes

      - name: Fix missing dependencies if needed
        ansible.builtin.apt:
          update_cache: yes
          state: present
        when: install_output.rc != 0

      - name: Ensure Nginx is installed
        ansible.builtin.command:
          cmd: dpkg -i {{ nginx_package }}
        when: install_output.rc != 0

      - name: Start and enable Nginx
        ansible.builtin.service:
          name: nginx
          state: started
          enabled: yes